In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns 
sns.set_style('whitegrid')
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix,classification_report

In [2]:
dataset = pd.read_csv('admitance.csv')

In [3]:
dataset

SAT Admitted
0    1363       No
1    1792      Yes
2    1954      Yes
3    1653       No
4    1593       No
..    ...      ...
163  1722      Yes
164  1750      Yes
165  1555       No
166  1524       No
167  1461       No

[168 rows x 2 columns]

In [4]:
x = dataset.iloc[:,[0]].values

In [5]:
x

array([[1363],
       [1792],
       [1954],
       [1653],
       [1593],
       [1755],
       [1775],
       [1887],
       [1893],
       [1580],
       [1857],
       [1880],
       [1664],
       [1364],
       [1693],
       [1850],
       [1633],
       [1634],
       [1636],
       [1855],
       [1987],
       [1997],
       [1422],
       [1508],
       [1720],
       [1879],
       [1634],
       [1802],
       [1849],
       [1764],
       [1460],
       [1675],
       [1656],
       [2020],
       [1850],
       [1865],
       [1664],
       [1872],
       [1654],
       [1393],
       [1587],
       [1631],
       [1931],
       [1370],
       [1810],
       [1414],
       [1761],
       [1477],
       [1486],
       [1561],
       [1549],
       [2050],
       [1697],
       [1543],
       [1934],
       [1385],
       [1670],
       [1735],
       [1634],
       [1777],
       [1550],
       [1715],
       [1925],
       [1842],
       [1786],
       [1435],
       [13

In [6]:
dataset['Admitted'] = dataset['Admitted'].map({'Yes':1,'No':0})

In [7]:
dataset

SAT  Admitted
0    1363         0
1    1792         1
2    1954         1
3    1653         0
4    1593         0
..    ...       ...
163  1722         1
164  1750         1
165  1555         0
166  1524         0
167  1461         0

[168 rows x 2 columns]

In [8]:
y = dataset.iloc[:,1].values

In [9]:
y

array([0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0,
       1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0,
       0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0,
       0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0,
       1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0], dtype=int64)

In [10]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=0)

In [11]:
x_train.shape

(134, 1)

In [12]:
x_test.shape

(34, 1)

In [13]:
from sklearn.neighbors import KNeighborsClassifier

In [14]:
model = KNeighborsClassifier(n_neighbors=5)

In [15]:
model.fit(x_train,y_train)

KNeighborsClassifier()

In [16]:
y_pred = model.predict(x_test)

In [17]:
y_pred

array([1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1,
       1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1], dtype=int64)

In [18]:
y_test

array([1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1,
       1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1], dtype=int64)

In [19]:
print(confusion_matrix(y_test,y_pred))

[[15  0]
 [ 1 18]]


In [20]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.94      1.00      0.97        15
           1       1.00      0.95      0.97        19

    accuracy                           0.97        34
   macro avg       0.97      0.97      0.97        34
weighted avg       0.97      0.97      0.97        34

