In [1]:
import numpy as np

In [2]:
arr = np.array([23,45,88,5,3,67,89,12,56])

In [3]:
arr.shape

(9,)

In [4]:
arr[2]

88

In [5]:
arr[5]

67

In [6]:
arr[2:6]

array([88,  5,  3, 67])

In [7]:
arr[5:]

array([67, 89, 12, 56])

In [8]:
arr

array([23, 45, 88,  5,  3, 67, 89, 12, 56])

In [9]:
arr[:4]

array([23, 45, 88,  5])

In [11]:
np.random.randint(1,100,25)

array([38, 36, 43, 53, 45, 85, 44, 18, 62, 87, 72, 18, 84, 48, 72, 75, 56,
       81, 34, 84, 16,  3, 78, 26, 25])

In [12]:
arr2 = np.random.randint(1,100,25)

In [13]:
arr2

array([53, 42, 65, 58, 57, 67, 96, 68,  1, 48,  6,  5, 89, 35, 39, 76,  2,
        6, 54, 78, 89, 50, 88, 54, 33])

In [14]:
arr2.shape

(25,)

In [15]:
arr3 = arr2.reshape(5,5)

In [16]:
arr3

array([[53, 42, 65, 58, 57],
       [67, 96, 68,  1, 48],
       [ 6,  5, 89, 35, 39],
       [76,  2,  6, 54, 78],
       [89, 50, 88, 54, 33]])

In [17]:
arr3.shape

(5, 5)

In [18]:
arr3[1:3,2:]

array([[68,  1, 48],
       [89, 35, 39]])

In [19]:
arr3[2:4,1:3]

array([[ 5, 89],
       [ 2,  6]])

In [20]:
arr3[:,0]

array([53, 67,  6, 76, 89])

In [21]:
arr3

array([[53, 42, 65, 58, 57],
       [67, 96, 68,  1, 48],
       [ 6,  5, 89, 35, 39],
       [76,  2,  6, 54, 78],
       [89, 50, 88, 54, 33]])

In [22]:
arr3[:,[0]]

array([[53],
       [67],
       [ 6],
       [76],
       [89]])

In [23]:
arr3[:,[0]].shape

(5, 1)

In [24]:
arr3

array([[53, 42, 65, 58, 57],
       [67, 96, 68,  1, 48],
       [ 6,  5, 89, 35, 39],
       [76,  2,  6, 54, 78],
       [89, 50, 88, 54, 33]])

In [25]:
arr3[:,[1,2]]

array([[42, 65],
       [96, 68],
       [ 5, 89],
       [ 2,  6],
       [50, 88]])

In [26]:
arr3[:,1:3]

array([[42, 65],
       [96, 68],
       [ 5, 89],
       [ 2,  6],
       [50, 88]])

In [27]:
arr3

array([[53, 42, 65, 58, 57],
       [67, 96, 68,  1, 48],
       [ 6,  5, 89, 35, 39],
       [76,  2,  6, 54, 78],
       [89, 50, 88, 54, 33]])

In [28]:
arr3[2]

array([ 6,  5, 89, 35, 39])

In [29]:
arr4 = np.array([1,2,2,3,4,4,5,3,3])

In [30]:
arr4

array([1, 2, 2, 3, 4, 4, 5, 3, 3])

In [31]:
arr4.shape

(9,)

In [32]:
np.mean(arr4)

3.0

In [33]:
np.var(arr4)

1.3333333333333333

In [34]:
np.std(arr4)

1.1547005383792515

In [35]:
np.sin(arr4)

array([ 0.84147098,  0.90929743,  0.90929743,  0.14112001, -0.7568025 ,
       -0.7568025 , -0.95892427,  0.14112001,  0.14112001])

In [36]:
np.cos(arr4)

array([ 0.54030231, -0.41614684, -0.41614684, -0.9899925 , -0.65364362,
       -0.65364362,  0.28366219, -0.9899925 , -0.9899925 ])

In [37]:
np.log(arr4)

array([0.        , 0.69314718, 0.69314718, 1.09861229, 1.38629436,
       1.38629436, 1.60943791, 1.09861229, 1.09861229])

In [38]:
np.exp(arr4)

array([  2.71828183,   7.3890561 ,   7.3890561 ,  20.08553692,
        54.59815003,  54.59815003, 148.4131591 ,  20.08553692,
        20.08553692])

In [39]:
# PANDAS 

In [40]:
my_list = [23,366,42]

In [42]:
label = ['a','b','c']

In [43]:
d = {'x':234,'y':56,'z':567}

In [45]:
d

{'x': 234, 'y': 56, 'z': 567}

In [46]:
arr1 = np.array([255,67,890])

In [2]:
import pandas as pd 

In [6]:
my_list = [23,366,42]

In [7]:
ser1 = pd.Series(my_list)

In [8]:
ser1

0     23
1    366
2     42
dtype: int64

In [9]:
type(ser1)

pandas.core.series.Series

In [10]:
ser2 = pd.Series(data=my_list,index=label)

NameError: name 'label' is not defined

In [11]:
ser2

NameError: name 'ser2' is not defined

In [54]:
arr1

array([255,  67, 890])

In [55]:
ser3 = pd.Series(arr1)

In [56]:
ser3

0    255
1     67
2    890
dtype: int32

In [57]:
d

{'x': 234, 'y': 56, 'z': 567}

In [58]:
ser4 = pd.Series(arr1)

In [59]:
ser4

0    255
1     67
2    890
dtype: int32

In [60]:
arr3

array([[53, 42, 65, 58, 57],
       [67, 96, 68,  1, 48],
       [ 6,  5, 89, 35, 39],
       [76,  2,  6, 54, 78],
       [89, 50, 88, 54, 33]])

In [61]:
my_list

[23, 366, 42]

In [62]:
arr3.shape

(5, 5)

In [63]:
# Dataframe

In [64]:
np.random.rand(4,5)

array([[0.47625864, 0.17234873, 0.89892252, 0.7535024 , 0.83421347],
       [0.8531038 , 0.1086068 , 0.60664461, 0.80834253, 0.65465056],
       [0.72741769, 0.87007327, 0.64341295, 0.68624337, 0.20615171],
       [0.28417281, 0.71049758, 0.53413056, 0.81212345, 0.41701492]])

In [65]:
df = pd.DataFrame(np.random.rand(4,5),columns=['ray','sonu','ramu','deep','john'],index=['a','b','c','d'])

In [66]:
df

ray      sonu      ramu      deep      john
a  0.778856  0.303553  0.355197  0.564749  0.439477
b  0.107597  0.072308  0.402431  0.253757  0.479366
c  0.719638  0.126348  0.643073  0.527651  0.353629
d  0.133374  0.322137  0.896712  0.598049  0.129044

In [67]:
df.shape

(4, 5)

In [68]:
type(df)

pandas.core.frame.DataFrame

In [73]:
df1 = pd.read_csv('prachi.csv')

In [74]:
df1

name  age  salary    city
0    sonu   23    5677  nagpur
1    monu   45   30000    pune
2    deep   45    3456   akola
3  sachin   20    4566   delhi

In [75]:
df2 = pd.read_csv('Social_Network_Ads.csv')

In [76]:
df2

User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

In [77]:
df2.shape

(400, 5)