In [1]:
import numpy as np 

In [2]:
arr = np.array([23,45,88,53,67,89,12,56])

In [3]:
arr.shape

(8,)

In [4]:
arr[2]

88

In [5]:
arr[5]

89

In [6]:
arr[2:6]

array([88, 53, 67, 89])

In [7]:
arr[5:]

array([89, 12, 56])

In [8]:
arr

array([23, 45, 88, 53, 67, 89, 12, 56])

In [9]:
arr[:4]

array([23, 45, 88, 53])

In [10]:
np.random.randint(1,100,25)

array([88, 41, 12, 39, 11, 61, 56, 22, 20, 76,  7, 66, 49, 17, 60, 41, 90,
       28, 79, 30, 49, 32, 45, 71, 46])

In [11]:
arr2 = np.random.randint(1,100,25)

In [12]:
arr

array([23, 45, 88, 53, 67, 89, 12, 56])

In [13]:
arr2.shape

(25,)

In [14]:
arr3 = arr2.reshape(5,5)

In [15]:
arr3

array([[34, 14, 61, 43,  7],
       [41, 52, 94, 72, 73],
       [64, 96, 18, 29, 10],
       [51, 15, 43, 61, 55],
       [53, 20, 44, 92, 32]])

In [16]:
arr3.shape

(5, 5)

In [17]:
arr3[1:3,2:]

array([[94, 72, 73],
       [18, 29, 10]])

In [18]:
arr3[2:4,1:3]

array([[96, 18],
       [15, 43]])

In [19]:
arr3[:,0]

array([34, 41, 64, 51, 53])

In [20]:
arr3

array([[34, 14, 61, 43,  7],
       [41, 52, 94, 72, 73],
       [64, 96, 18, 29, 10],
       [51, 15, 43, 61, 55],
       [53, 20, 44, 92, 32]])

In [21]:
arr3[:,[0]]

array([[34],
       [41],
       [64],
       [51],
       [53]])

In [22]:
arr3[:,[0]].shape

(5, 1)

In [23]:
arr3

array([[34, 14, 61, 43,  7],
       [41, 52, 94, 72, 73],
       [64, 96, 18, 29, 10],
       [51, 15, 43, 61, 55],
       [53, 20, 44, 92, 32]])

In [24]:
arr3[:,[1,2]]

array([[14, 61],
       [52, 94],
       [96, 18],
       [15, 43],
       [20, 44]])

In [26]:
arr3[:,1:3]

array([[14, 61],
       [52, 94],
       [96, 18],
       [15, 43],
       [20, 44]])

In [27]:
arr3

array([[34, 14, 61, 43,  7],
       [41, 52, 94, 72, 73],
       [64, 96, 18, 29, 10],
       [51, 15, 43, 61, 55],
       [53, 20, 44, 92, 32]])

In [28]:
arr3[2]

array([64, 96, 18, 29, 10])

In [29]:
arr4 = np.array([1,2,2,3,4,4,5,3,3])

In [30]:
arr4

array([1, 2, 2, 3, 4, 4, 5, 3, 3])

In [31]:
arr4.shape

(9,)

In [32]:
np.mean(arr4)

3.0

In [33]:
np.var(arr4)

1.3333333333333333

In [34]:
np.std(arr4)

1.1547005383792515

In [35]:
np.sin(arr4)

array([ 0.84147098,  0.90929743,  0.90929743,  0.14112001, -0.7568025 ,
       -0.7568025 , -0.95892427,  0.14112001,  0.14112001])

In [36]:
np.cos(arr4)

array([ 0.54030231, -0.41614684, -0.41614684, -0.9899925 , -0.65364362,
       -0.65364362,  0.28366219, -0.9899925 , -0.9899925 ])

In [37]:
np.log(arr4)

array([0.        , 0.69314718, 0.69314718, 1.09861229, 1.38629436,
       1.38629436, 1.60943791, 1.09861229, 1.09861229])

In [38]:
np.exp(arr4)

array([  2.71828183,   7.3890561 ,   7.3890561 ,  20.08553692,
        54.59815003,  54.59815003, 148.4131591 ,  20.08553692,
        20.08553692])

In [39]:
# Pandas

In [40]:
my_list = [23,366,42]

In [41]:
label = ['a','b','c','d']

In [42]:
d = {'x':234,'y':56,'z':567}

In [43]:
d

{'x': 234, 'y': 56, 'z': 567}

In [44]:
arr1 = np.array([255,67,890])

In [45]:
import pandas as pd

In [54]:
my_list = [23,366,42]

In [55]:
ser1 = pd.Series(my_list)

In [56]:
ser1

0     23
1    366
2     42
dtype: int64

In [57]:
type(ser1)

pandas.core.series.Series

In [58]:
ser2 = pd.Series(data=my_list,index=label)

ValueError: Length of values (3) does not match length of index (4)